language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "mykovolod-github"
    token:
      secure: "5f78ed8a9a02fc70360c8629276b6005f43aaba9"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)