language: java

addons:
  sonarcloud:
    organization: "mykovolod-github"
    token:
      secure: 5f78ed8a9a02fc70360c8629276b6005f43aaba9
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  # the following command line builds code test coverage report
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)